### ISSUE TITLE
Misunderstanding with the package

### ISSUE THREAD

**Issue by besstilahun** [rinvex/laravel-subscriptions#100]
Hey guys! i want to add subscription functionality to my project. i don't have that much experiance on laravel, and by your docs i have gone from the installation upto adding the triat in my User model. what is challenging for me is, where should i put my *$plan*?, is it in my model or in my controller, please guid me. i have searched for example on your package but found none!

**Comment by Omranic** [comment]
Hello @besstilahun 
Thank you for your message, to create a plan you can add it from your controller, follow the steps here and you should be ok 🙂  feel free to re-open this issue if you still have further questions!
