### ISSUE TITLE
Features are related to only one plan

### ISSUE THREAD

**Issue by undjike** [rinvex/laravel-subscriptions#101]
Why is a feature related to a plan ? Commonly, many plans can grant access to a feature...
For instance, both VIP and standard plans grant access to **Email Notifications **

**Comment by undjike** [comment]
Why not think of creating a feature migration and a many to many relation for mapping features and plans ?

**Comment by undjike** [comment]
Okay... Let me just close this issue. Seams like it's out of the scope of this project.

**Comment by Omranic** [comment]
Actually I like this idea, and I'm considering it in a future release.

I would be happy to consider PRs adding this adjustment to the package 🙂

**Comment by mirza4027** [comment]
public function getFeatureLimit($subscriptions, $featureType)
  {
    $limit = 0;
    if(!empty($subscriptions)) {

      foreach ($subscriptions as $subscription) {

        $plan = app('rinvex.subscriptions.plan')->find($subscription->plan_id);
        $hasFeatureType = $plan->features()->where('slug', $featureType . '_' . $plan->slug)->get();
        if(!empty($hasFeatureType)) {
          $limit += $subscription->getFeatureValue($featureType . '_' . $plan->slug);
        } else {
          continue;
        }
      }
    }

    return $limit;
  }
  
  My workaround for this is currently where I check multiple plans having the same feature. Concatenated the feature type with the plan slug, which is basically starting the plan feature name with the common prefix. In your case your every plan needs to have a feature starting with 'email_notifications_'.$plan_slug

**Comment by Omranic** [comment]
I'd be happy to consider any PRs to implement this feature, all PRs are most welcome 😉
