### ISSUE TITLE
Only supports Laravel 7?

### ISSUE THREAD

**Issue by xdimension** [rinvex/laravel-subscriptions#102]
Does the newest version only support Laravel 7? Is there any way to install it for Laravel 6 or what version supports Laravel 6?

Error message:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.18.19
    - Conclusion: don't install laravel/framework v6.18.19
    - rinvex/laravel-subscriptions v4.0.0 requires illuminate/support ^7.0.0

**Comment by Omranic** [comment]
Thank you @xdimension for your question. Latest version v4.x supports Laravel v7.x and up, and requirer PHP v7.4 upwards. If you want to Laravel v6.x compatibility, then use the v3.x of this package.
