### ISSUE TITLE
not working with laravel 5.8

### ISSUE THREAD

**Issue by uttamsingh** [rinvex/laravel-subscriptions#104]
Problem 1
    - Installation request for rinvex/laravel-subscriptions ^4.1 -> satisfiable by rinvex/laravel-subscriptions[v4.1.0].
    - Conclusion: remove laravel/framework v5.8.38
    - rinvex/laravel-subscriptions v4.1.0 requires illuminate/support ^7.0.0 -> satisfiable by illuminate/support[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.2.0, v7.2.1, v7.2.2, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2], laravel/framework[7.x-dev].
    - Can only install one of: laravel/framework[v5.8.38, 7.x-dev].
    - don't install laravel/framework v5.8.38|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.0.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.0.1
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.0.2
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.0.3
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.0.4
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.0.5
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.0.6
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.0.7
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.0.8
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.1.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.1.1
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.1.2
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.1.3
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.10.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.10.1
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.10.2
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.10.3
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.11.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.12.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.13.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.14.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.14.1
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.15.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.16.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.16.1
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.2.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.2.1
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.2.2
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.3.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.4.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.5.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.5.1
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.5.2
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.6.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.6.1
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.6.2
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.7.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.7.1
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.8.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.8.1
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.9.0
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.9.1
    - don't install laravel/framework v5.8.38|don't install illuminate/support v7.9.2
    - Installation request for laravel/framework (installed at v5.8.38, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.38].

**Comment by nipunparallax** [comment]
You are trying to install v4.1 with Laravel 5.8 . You need to use older version of this package for Laravel 5.8. Just run like this 
`composer require rinvex/laravel-subscriptions:3.*`

**Comment by nipunTharuksha** [comment]
You are trying to install v4.1 with Laravel 5.8 . You need to use older version of this package for Laravel 5.8. Just run like this composer require rinvex/laravel-subscriptions:3.*

**Comment by nipunTharuksha** [comment]
You are trying to install v4.1 with Laravel 5.8 . You need to use older version of this package for Laravel 5.8. Just run like this `composer require rinvex/laravel-subscriptions:3.*`

**Comment by undjike** [comment]
The problem remained using Laravel 7. I'm not able to install the package.

**Comment by nipunparallax** [comment]
Well, the package is working with Laravel 7. There is a way to install the package for Laravel 5.8 by installing an older version of this package(3.*). Just give it a try `composer require rinvex/laravel-subscriptions:3.*`

**Comment by Omranic** [comment]
Yes, @nipunparallax is right.

For now we're supporting only latest stable release of Laravel, which is v7.x
Another way around is to fork the package and lower the dependencies, and it should work fine, I don't think there will be an issue.
