### ISSUE TITLE
Issue while recording usage

### ISSUE THREAD

**Issue by debuGhy** [rinvex/laravel-subscriptions#106]
I am getting the following error:

Call to a member function recordFeatureUsage() on null.
Controller code looks like this--
````
public function test(){
        $user = User::find(16);
        $plan = app('rinvex.subscriptions.plan')->find(1);
        //$user->newSubscription('Basic', $plan);
        //dd($user->imagesCount);
        $user->subscription('basic')->recordFeatureUsage('add-2-photos', $user->imagesCount);
    }
````
The above works fine in localhost but in live server it gives me error.
Can anyone tell me what is it?

**Comment by nipunTharuksha** [comment]
Check  `$user->imagesCount` is null first

**Comment by Omranic** [comment]
You can simply put your code inside an if condition, example:
```if ($user->subscription('basic')) {
        // Your code here
}
```
