### ISSUE TITLE
The Documentation is not Up To Date with the Package

### ISSUE THREAD

**Issue by Elshaden** [rinvex/laravel-subscriptions#107]
Hello

I am having many problems following the documentation. , the documentation does not really reflect what is in your code:

I advise any user to dig into the code and find out  usage methods. 
or fork it and change your code to adjust to your needs.

The package is a great start for an improved version.

**Comment by tumelo-mapheto** [comment]
I second your statement; Superb package, but the documentation does need to improve.

**Comment by insign** [comment]
PR are always welcome. Even if it is just a typo.

**Comment by Omranic** [comment]
Thank you for your feedback, I'd be happy to consider any PRs that improve the code or documentation. All PRs are most welcome 😉
