### ISSUE TITLE
Dosn't install in Laravel 7

### ISSUE THREAD

**Issue by MohammadEmoney** [rinvex/laravel-subscriptions#108]
Hi 
I tried to install the package in laravel 7 but I got error

`Problem 1
    - Conclusion: remove laravel/framework v7.21.0
    - Conclusion: don't install laravel/framework v7.21.0
    - rinvex/laravel-subscriptions v3.0.0 requires illuminate/database ^6.0.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-subscriptions v3.0.1 requires illuminate/database ^6.0.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-subscriptions v3.0.2 requires illuminate/database ^6.0.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - Can only install one of: laravel/framework[6.x-dev, v7.21.0].
    - don't install illuminate/database 6.x-dev|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.0.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.0.1|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.0.2|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.0.3|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.0.4|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.1.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.10.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.11.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.12.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.13.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.13.1|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.14.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.15.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.15.1|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.16.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.17.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.17.1|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.1|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.10|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.11|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.12|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.13|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.14|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.15|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.16|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.17|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.18|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.19|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.2|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.20|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.21|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.22|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.23|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.24|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.25|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.26|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.3|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.4|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.5|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.6|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.7|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.8|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.18.9|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.2.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.3.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.4.1|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.5.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.5.1|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.5.2|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.6.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.6.1|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.6.2|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.7.0|don't install laravel/framework v7.21.0
    - don't install illuminate/database v6.8.0|don't install laravel/framework v7.21.0
    - Installation request for laravel/framework (locked at v7.21.0, required as ^7.0) -> satisfiable by laravel/framework[v7.21.0].
    - Installation request for rinvex/laravel-subscriptions ^3.0 -> satisfiable by rinvex/laravel-subscriptions[v3.0.0, v3.0.1, v3.0.2].`

but it was fine with laravel 6.2 though!

**Comment by bpuig** [comment]
You have to install v4 , not v3 (this one is not compatible with laravel 7)

**Comment by Omranic** [comment]
True, Laravel v7.x is supported in v4.x of this package, which also requires PHP v7.4 or up.
