### ISSUE TITLE
Slugs from translations may rise issues

### ISSUE THREAD

**Issue by bpuig** [rinvex/laravel-subscriptions#109]
Hello,
I'm developing a project and now I'm starting to get knee deep into the package. I've found something that might create problems: slugs.

Docs say that slugs can be used as an identifier "key" to a subscription. (See examples: `$user->newSubscription('main', $plan)`, `$user->subscription('main')->canUseFeature('listings')`). 
So, slug it's kind of "hardcoded" into our applications to identify main or other subscriptions. Leaving aside PR #76 that would fix some of the issues this rises to me the question of why is `name` translatable? Or if we keep it like that because is logical to have a multilanguage app, why is `slug` made from name? We can end up with a _principal_, _main_, _haupt_ slug... whatever name in the language that was input. So it defeats the docs purpose of using it as identifier key.

In my opinion, everything it correct as is right now only if we add a column called `identifier`, `subscription_key` or whatever you like most and then retrieve our subscriptions by it instead of slug (and change PR #76 to this new key and leave slug). And then everyone will do their own logic to fill identifier.

I can try it and do a new PR if it seems logical to you.

**Comment by Omranic** [comment]
Thank you for your patience, this is related to #76 & #110 (fix under review, let's keep the discussion on #76)
