### ISSUE TITLE
Migration Problem when upgrading the version

### ISSUE THREAD

**Issue by ipanardian** [rinvex/laravel-subscriptions#111]
Hello, 
I was upgrade laravel  from 5.8 to 7.25 but I've problem when upgrading rinvex laravel subscription from 2.1 to 4.1. I have a problem with migration.

When run CI/CD pipeline this error occurs:

`SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'plans' already exists`

Because i've already that table but i want to run migration for update my own table. 

Existing file in my migration folder:
2019_06_24_112755_create_plans_table

migrate:status
2020_01_01_000001_create_plans_table

what should i do? Thanks

**Comment by ipanardian** [comment]
Is it good idea to insert 2020_01_01_000001_create_plans_table to the database?

**Comment by Omranic** [comment]
Sorry for the inconvenience, yes inserting `2020_01_01_000001_create_plans_table` into `migrations` database table should solve it.
