### ISSUE TITLE
When creating new plan in pgsql getting "error operator does not exist: json = unknown"

### ISSUE THREAD

**Issue by Nandi1234** [rinvex/laravel-subscriptions#113]
SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: json = unknown
LINE 1: select count(*) as aggregate from "plans" where "name" = $1
                                                               ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: select count(*) as aggregate from "plans" where "name" = Pro)

**Comment by Omranic** [comment]
Thank you for your patience, I'm not sure I understand your request correctly, would you kindly explain if that's something you're still looking for, and feel free to re-open this issue?
