### ISSUE TITLE
Can't customize the default migrations

### ISSUE THREAD

**Issue by malicoo** [rinvex/laravel-subscriptions#114]
I published and edited  the default migrations but when I run artisan migrate, the migrations files provided by the package is picked over the edited migrations.

Especially for devs using uuid.

**Comment by malicoo** [comment]
```php
namespace Rinvex\Subscriptions\Providers;
...
class SubscriptionsServiceProvider extends ServiceProvider{

    public function boot(): void{
        $this->publishesConfig('rinvex/laravel-subscriptions');
        $this->publishesMigrations('rinvex/laravel-subscriptions');
        // ! $this->autoloadMigrations('rinvex/laravel-subscriptions') || $this>loadMigrationsFrom(__DIR__.'/../../database/migrations');
    }
```

Commenting the line above solved the problem but someone needs to make a pull request for this.

**Comment by malicoo** [comment]
Sorry. 
False alarm

**Comment by Omranic** [comment]
You can set `autoload_migrations` to `false`

https://github.com/rinvex/laravel-subscriptions/blob/master/config/config.php#L8
