### ISSUE TITLE
Update to support Laravel 8

### ISSUE THREAD

**Issue by hgferreira** [rinvex/laravel-subscriptions#117]
Hi,

Is it possible to update to support Laravel 8? It should be a quick fix.

Thank you!

**Comment by wimil** [comment]
same....

**Comment by Crisis2010** [comment]
+

**Comment by Djuki** [comment]
+1

**Comment by masitings** [comment]
Up up

**Comment by alikemalcivelek** [comment]
+1

**Comment by nivv** [comment]
I've added a pull request, there are no tests, and I have not tested the package after the updates. #118

**Comment by schranzer235** [comment]
+🥰

**Comment by bassem-shoukry** [comment]
any updates?

**Comment by nivv** [comment]
> any updates?

Project seems dead. I'd look for a replacement, or fork it and maintain it yourself

**Comment by bassem-shoukry** [comment]
> 
> 
> > any updates?
> 
> project seems dead. I'd look for a replacement, or fork it and maintain it yourself

okay thanks

**Comment by insign** [comment]
I don't belivie it is dead. Well, at least the main reason, which is abandon the project. The author don't give the proper attention for years and his updates after months are LIKE "go f... everybody, now I want php 7.4, just because it looks good, if you want..." (#90, #98)

**Comment by schranzer235** [comment]
First off, what i did, i wrote an kind email directly to rinvex without a response.

In case it could help anyone too. Here is my solution which has a few downsides and is not perfect at all.

1. Modify your composer.json

```
"autoload": {
        "psr-4": {
....
            "Rinvex\\": "support/rinvex"
        },
    },
```

2. Create a directory /support/rinvex or anything you would like
3. Move the src Code from rinvex packages into their corresponding directory ( /support/rinvex/Categories|Subscriptions|Support)
4. Decide if you want to keep rinvex model validation (I removed it). You might have to do some more work here too to get it working (e.g. you'll need another third party dependency)
5. Integrate every dependency that any rinvex package use in your composer.json (like spatie/laravel-sluggable, kalnoy/nestedset, ...)
6. Run your tests, if you don't have any, write them.

My win for this solution, i don't have to modify my existing source code and can leave it, as it is. For instance, i'm mostly subclassing package models like seen below

```
<?php

namespace App\Shared\Models;

class Category extends \Rinvex\Categories\Models\Category
{
}
```

I don't like this approach but when rinvex comes back i can easily switch back and re-run my tests.

Good luck everyone in surviving this nightmare

**Comment by mojtabaahn** [comment]
+1

**Comment by Omranic** [comment]
Hello, thank you for your patience, this is now done! Check latest release!!

This package now supports Laravel v8, PHP v8, Composer v2, enjoy 🥳

CC @mojtabaahn @schranzer235 @insign @bassem-shoukry @nivv @schranzer235 @alikemalcivelek @masitings @Djuki @Crisis2010 @wimil @hgferreira

**Comment by bassem-shoukry** [comment]
thanks @Omranic
