### ISSUE TITLE
Laravel 8 - another package

### ISSUE THREAD

**Issue by binaryk** [rinvex/laravel-subscriptions#122]
Hi there,

considering this package is not maintained for a long time and people didn't get any feedback on https://github.com/rinvex/laravel-subscriptions/issues/117, I forked and added support for Laravel 8.

You may use: `binarcode/rinvex-laravel-subscriptions@4.2.1` for Laravel 8 until @Omranic will update this.

Check it out: https://github.com/BinarCode/laravel-subscriptions

Thanks.

**Comment by insign** [comment]
Do you fix https://github.com/rinvex/laravel-categories/issues/85 and https://github.com/rinvex/laravel-subscriptions/issues/117 questions?

**Comment by hirenreshamwala** [comment]
Publish fail in `binarcode/rinvex-laravel-subscriptions`.

Getting following error when execute `php artisan rinvex:publish:subscriptions`

"Unable to locate publishable resources."

**Comment by hirenreshamwala** [comment]
> Publish fail in `binarcode/rinvex-laravel-subscriptions`.
> 
> Getting following error when execute `php artisan rinvex:publish:subscriptions`
> 
> "Unable to locate publishable resources."

You should to replace package name in `SubscriptionsServiceProvider`

```
$this->publishesConfig('rinvex/laravel-subscriptions');
        $this->publishesMigrations('rinvex/laravel-subscriptions');
        ! $this->autoloadMigrations('rinvex/laravel-subscriptions') || $this->loadMigrationsFrom(__DIR__.'/../../database/migrations');
```

TO

```
$this->publishesConfig('binarcode/laravel-subscriptions');
        $this->publishesMigrations('binarcode/laravel-subscriptions');
        ! $this->autoloadMigrations('binarcode/laravel-subscriptions') || $this->loadMigrationsFrom(__DIR__.'/../../database/migrations');
```

**Comment by binaryk** [comment]
@hirenreshamwala addressed it. Check it out: https://github.com/BinarCode/laravel-subscriptions/releases/tag/4.2.6. I'm using it on production.

**Comment by patiefariey** [comment]
Still giving the same error. 

"Unable to locate publishable resources."

have installed the latest version

**Comment by smkhan321** [comment]
@binaryk how did you managed to work it out, I am also getting the same error

> Publish fail in `binarcode/rinvex-laravel-subscriptions`.
> 
> Getting following error when execute `php artisan rinvex:publish:subscriptions`
> 
> "Unable to locate publishable resources."

**Comment by smkhan321** [comment]
temporarily made it work by doing following steps, in case someone needs it

copied config from the package into main `configs` directory renamed it to `rinvex.php` and modified following
`<?php

declare(strict_types=1);

return [

    'subscriptions' => [
        // Manage autoload migrations
        'autoload_migrations' => false, // changed to false to follow local migrations path

        // Subscriptions Database Tables
        'tables' => [

            'plans' => 'plans',
            'plan_features' => 'plan_features',
            'plan_subscriptions' => 'plan_subscriptions',
            'plan_subscription_usage' => 'plan_subscription_usage',

        ],

        // Subscriptions Models
        'models' => [

            'plan' => \Rinvex\Subscriptions\Models\Plan::class,
            'plan_feature' => \Rinvex\Subscriptions\Models\PlanFeature::class,
            'plan_subscription' => \Rinvex\Subscriptions\Models\PlanSubscription::class,
            'plan_subscription_usage' => \Rinvex\Subscriptions\Models\PlanSubscriptionUsage::class,

        ],
    ],
];`

copied all migrations from package to main `database/migrations/rinvex/laravel-subscriptions`

**Comment by Omranic** [comment]
Hello, thank you for your patience, this is now done! Check latest release!!

This package now supports Laravel v8, PHP v8, Composer v2, enjoy 🥳

CC @insign @hirenreshamwala @binaryk @smkhan321 @patiefariey

**Comment by binaryk** [comment]
Huh, thanks @Omranic , thankfully you're good!
