### ISSUE TITLE
How to implement Special discounts

### ISSUE THREAD

**Issue by Jahchap** [rinvex/laravel-subscriptions#130]
Please I am new to this awesome package and would like to know how to modify it to include discounts using coupons.

**Comment by Omranic** [comment]
Discounts & coupons are kind of more related to payments, which is out of this package's scope at the time being. Please check these considerations in the docs https://github.com/rinvex/laravel-subscriptions#considerations

But I'm willing to re-consider if someone is willing to propose a draft PR. Thank you for using this package, let me know if you need any help.

**Comment by insign** [comment]
Looks like a service for the gateway... Stripe, for instance.

Em seg, 4 de jan de 2021 18:27, Abdelrahman Omran <notifications@github.com>
escreveu:
