### ISSUE TITLE
not everything is perfect, but i like this source code.

### ISSUE THREAD

**Issue by h-zone** [rinvex/laravel-subscriptions#131]
- there are not enough files included in the package to manage data through Laravel Nova

- I would like to see integration files in laravel nova

- as a result, we get a compressed dataset for each plan. at the same time, it is necessary to take into account that if the property is absent, but is necessary for the operation of the system, the property must return null

- really a discussion of the need for a trial and other optional features that drag the local need for hardcoding.

ps: this is the personal vision of the package by the fresh user. if and / or when something changes according to the wishes, it will be great!

thx for great job !

**Comment by Omranic** [comment]
Thank you @h-zone for your feedback.

Currently we're not using Laravel Nova, but I would be happy to consider any PRs adding integration for this package with it 🙂
