### ISSUE TITLE
I can't install package on laravel 8

### ISSUE THREAD

**Issue by mrmostafaeei** [rinvex/laravel-subscriptions#133]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rinvex/laravel-support v5.0.1 requires felixkiss/uniquewith-validator ^3.4.0 -> satisfiable by felixkiss/uniquewith-validator[3.4.0].
    - rinvex/laravel-support v5.0.3 requires rinvex/tmp-watson-validating ^6.0.0 -> satisfiable by rinvex/tmp-watson-validating[6.0.0, v6.0.1, 6.0.2, 6.0.3].
    - rinvex/laravel-support v5.0.2 requires rinvex/tmp-felixkiss-uniquewith-validator 3.4.0 -> satisfiable by rinvex/tmp-felixkiss-uniquewith-validator[3.4.0].
    - rinvex/laravel-subscriptions v5.0.0 requires php ^7.4.0 -> your php version (8.0.1) does not satisfy that requirement.
    - rinvex/laravel-support v5.0.0 requires php ^7.4.0 -> your php version (8.0.1) does not satisfy that requirement.
    - felixkiss/uniquewith-validator 3.4.0 requires php ^7.1.3 -> your php version (8.0.1) does not satisfy that requirement.
    - rinvex/tmp-felixkiss-uniquewith-validator 3.4.0 requires php ^7.1.3 -> your php version (8.0.1) does not satisfy that requirement.
    - rinvex/tmp-watson-validating[6.0.0, ..., 6.0.2] require php ^7.3 -> your php version (8.0.1) does not satisfy that requirement.
    - rinvex/tmp-watson-validating 6.0.3 requires php ^7.3 || v8.0.0 -> your php version (8.0.1) does not satisfy that requirement.
    - rinvex/laravel-subscriptions v5.0.1 requires rinvex/laravel-support ^5.0.0 -> satisfiable by rinvex/laravel-support[v5.0.0, v5.0.1, v5.0.2, v5.0.3].
    - Root composer.json requires rinvex/laravel-subscriptions ^5.0 -> satisfiable by rinvex/laravel-subscriptions[v5.0.0, v5.0.1].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Please update this package for install on laravel 8**

**Comment by Omranic** [comment]
That was an issue with one of the dependencies `rinvex/tmp-felixkiss-uniquewith-validator`, which is now fixed, please try again and let me know if you still have any issues.
