### ISSUE TITLE
[Bug] Period class has default length 1 when passing 0

### ISSUE THREAD

**Issue by lucianholt97** [rinvex/laravel-subscriptions#134]
Having a plan without a trial period, the trial_period is 0.
Lines 60-63 in the Period class:
```
if ($count > 0) {
     $this->period = $count;
}
```
This leads to a confusing default trial length of one day in my case.
Are there any reasons you chose to have this if statement?

Nevertheless, thank you for providing this package. It is very helpful.

**Comment by Omranic** [comment]
Thank you for your patience, this is now fixed in https://github.com/rinvex/laravel-subscriptions/commit/a83c765e227e172d5e893983c082db8e080ba6eb

Now it should add skip trial period if it's set to `0` as expected.
