### ISSUE TITLE
[Bug] PlanSubscription has no scope method: byFeatureSlug

### ISSUE THREAD

**Issue by DJEDAINI** [rinvex/laravel-subscriptions#136]
Call to undefined method Illuminate\Database\Eloquent\Relations\HasMany::byFeatureSlug()

**Comment by Omranic** [comment]
Similar to #43 #48 #62 #65 #136 #137 and was fixed previously on 0714e73, the fix already exists on the `develop` branch.

I'll tag a new version to merge the fix from `develop` to `master` 👍 

Sorry for the delay, and thank you for your patience!

@DJEDAINI

Check here for details 
https://github.com/rinvex/laravel-subscriptions/blob/c11e6bb85fcd5dcf706cb7544e0d375654868bbb/src/Models/PlanSubscriptionUsage.php#L132-L137
