### ISSUE TITLE
This project is dead

### ISSUE THREAD

**Issue by tjhunkin** [rinvex/laravel-subscriptions#140]

**Comment by Omranic** [comment]
It's funny that someone who never contributed to the project in any way or form, never posted an issue, never asked for help, never helped someone else to just open a ticket with no constructive criticism, and just saying the project is dead! Regardless of being a false and wrong claim, **what's the point from your claim anyway?!**

Buddy, if you want to help, please go ahead, I would love to have you contributing to the project, if you've any feedback that can make this project better, please post it, someone could benefit from it, but it's not nice to go around open source projects that people spend time and effort developing without asking for returns and throw false claims that doesn't contribute with any positive impact! If you can't or won't help, at least posting a nice encouraging word would be better :)

**Comment by Omranic** [comment]
It's funny that someone who never contributed to the project in any way or form, never posted an issue, never asked for help, never helped someone else to just open a ticket with no constructive criticism, and just saying the project is dead! Regardless of being a false and wrong claim, **what's the point from your claim anyway?!**

Buddy, if you want to help, please go ahead, I would love to have you contributing to the project, if you've any feedback that can make this project better, please post it, someone could benefit from it, but it's not nice to go around open source projects that people spend time and effort developing without asking for returns and throw false claims that doesn't contribute with any positive impact! If you can't or won't help, **at least posting a nice encouraging word would be better 🙂 **

**Comment by Omranic** [comment]
It's funny that someone who never contributed to the project in any way or form, never posted an issue, never asked for help, never helped someone else to just open a ticket with no constructive criticism, and just saying the project is dead! Regardless of being a false and wrong claim, **what's the point from your claim anyway?!**

Buddy, if you want to help, please go ahead, I would love to have you contributing to the project, if you've any feedback that can make this project better, please post it, someone could benefit from it, but it's not nice to go around open source projects that people spend time and effort developing without asking for returns and throw false claims that doesn't contribute with any positive impact! If you can't or won't help, **at least posting a nice encouraging word would be better 🙂  **

**Comment by Omranic** [comment]
It's funny that someone who never contributed to the project in any way or form, never posted an issue, never asked for help, never helped someone else to just open a ticket with no constructive criticism, and just saying the project is dead! Regardless of being a false and wrong claim, **what's the point from your claim anyway?!**

Buddy, if you want to help, please go ahead, I would love to have you contributing to the project, if you've any feedback that can make this project better, please post it, someone could benefit from it, but it's not nice to go around open source projects that people spend time and effort developing without asking for returns and throw false claims that doesn't contribute with any positive impact! If you can't or won't help, **at least posting a nice encouraging word would be better** 🙂

**Comment by tjhunkin** [comment]
Is it wrong to assume that it's dead if you don't respond to issues?
Why create a package and not support it?

It's a major frustration for someone to use your package, they run into an issue then there's just radio silence.

How about you put more effort into responding to issues?

https://github.com/rinvex/laravel-subscriptions/issues/124 ipanardian opened this issue on Nov 5, 2020
https://github.com/rinvex/laravel-subscriptions/issues/134 lucianholt97 opened this issue 27 days ago
https://github.com/rinvex/laravel-subscriptions/issues/138 DJEDAINI opened this issue 24 days ago
https://github.com/rinvex/laravel-subscriptions/issues/139 wojciechgabrys opened this issue 9 days ago

**Comment by Omranic** [comment]
You didn't answer the simple question above: **what's the point from your claim anyway?!**
How's your post helping the project or any of its users?! Educate me..

Debating with you won't add any value to this package or anyone else.
**Again buddy, if you want to help, go ahead and at least triage the issues you mentioned above, so we can prioritize what's critical and what's not, or at least have a real positive impact by sending tested PRs that could be merged and help everyone.**
