### ISSUE TITLE
mongodb support

### ISSUE THREAD

**Issue by tolgatasci** [rinvex/laravel-subscriptions#141]
Hello, I've made some changes for myself. This was necessary for me as I was using mongodb. If our system is mongodb, you can also use it.
All almost the same uses. Have a look at user.php.

We are grateful to the person who wrote this repository. We would be very happy if support for Mongodb is provided.

[https://www25.zippyshare.com/v/uznrzm0J/file.html
](https://www25.zippyshare.com/v/uznrzm0J/file.html
)

**Comment by Omranic** [comment]
Thank you @tolgatasci , I would be happy to look into the changes if you can submit a PR to this repo :)
