### ISSUE TITLE
Does it work with multiple users?

### ISSUE THREAD

**Issue by WNeuteboom** [rinvex/laravel-subscriptions#144]
Maybe i'm using it wrong, but I think it doesn't really work with multiple users.

I created a plan, with features.
Adding plans to user goes fine. 

But when searching $user->subscription('main')->canUseFeature('listings') it returns null;
That has to do with all new user subscriptions get main-1, main-2, main-3.
So i cant search for subscribtion('main') for user 3. Because it has other slug.

Now i have to loop through all the slugs in order to find it.

Please tell me what to do.

Thanks Wouter

**Comment by Omranic** [comment]
Short answer: Yes it work with multiple users.

Long answer: This is related to another issue (not fixed yet), reported in #69 & #76 (will fix it soon)
