### ISSUE TITLE
column user in  subscriptions.models.plan_subscription is changed !

### ISSUE THREAD

**Issue by abdullahessam** [rinvex/laravel-subscriptions#145]
i got an error after i make composer update about column subscriber not found after debuging i found that 
rinvex.subscriptions.models.plan_subscription  table 
            $table->morphs('subscriber');
changed from user to  subscriber
and the subscription function in the HasSubscriptions trait 

the solution for me i just override the  subscriptions relation function  in my model morph column name to user 

  public function subscriptions(): MorphMany
    {
        return $this->morphMany(config('rinvex.subscriptions.models.plan_subscription'), 'user', 'user_type', 'user_id');
    }

**Comment by Omranic** [comment]
Sorry about that breaking change. Details about the change, and a proposed solution could be found here https://github.com/rinvex/laravel-subscriptions/commit/c47c8567bb81f302a8a992b1030c414392706a02
