### ISSUE TITLE
Could not install rinvex/tmp-felixkiss-uniquewith-validator

### ISSUE THREAD

**Issue by ipanardian** [rinvex/laravel-subscriptions#148]
Hi,
Suddenly i got this on my pipeline build. Is there something wrong? can't find rinvex/tmp-felixkiss-uniquewith-validator
![image](https://user-images.githubusercontent.com/415225/116838538-e9f02280-abf8-11eb-99d5-c356314fa2cc.png)

Please fix this ASAP, thanks

**Comment by Omranic** [comment]
Install latest stable release, you shouldn't get any issues. This is fixed already and is working fine.

`composer require rinvex/laravel-subscriptions`

**Comment by insign** [comment]
`composer remove rinvex/laravel-subscriptions`

then

`composer require rinvex/laravel-subscriptions`

worked for me.
