### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by granitebps** [rinvex/laravel-subscriptions#149]
Got this error message when installing this package
![image](https://user-images.githubusercontent.com/44967965/116838731-ae098d00-abf9-11eb-88b3-4ddebd12606b.png)
The https://github.com/rinvex/tmp-felixkiss-uniquewith-validator package is not found

**Comment by boryn** [comment]
I just installed it with `composer require rinvex/laravel-subscriptions` and had no issues.

**Comment by Omranic** [comment]
@granitebps please install latest stable release, you should not get any issues.
