### ISSUE TITLE
How to clear Eloquent cache in rinvex/subscription

### ISSUE THREAD

**Issue by Anichur25** [rinvex/laravel-subscriptions#150]

**Comment by Omranic** [comment]
What eloquent cache do you mean?

This package doesn't use any custom caching strategies, if you're using Laravel cache, then you can manage it as usual. Check the official Laravel Cache documentation here https://laravel.com/docs/8.x/cache

And feel free to reopen this issue if you still need any further assistance.

**Comment by Anichur25** [comment]
@Omranic  thank you so much for your valuable suggestion.
