### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by yefta-me** [rinvex/laravel-subscriptions#153]
Hi,

when running `php artisan rinvex:publish:subscriptions` I got the following message:

```
Unable to locate publishable resources.
Publishing complete.
Unable to locate publishable resources.
Publishing complete.
```

Already ran dumpautoload and artisan clear-compiled. I'm using php7.3.
Thank you!

**Comment by JayteeNZ** [comment]
+1 for this. v3

**Comment by Omranic** [comment]
Thank you for your question, however v3 is no longer supported, but you can backport the updates from v5 if you want, as this is already fixed in latest releases.
