### ISSUE TITLE
Error in downloading dependency 

### ISSUE THREAD

**Issue by muhamedRadwan** [rinvex/laravel-subscriptions#154]
When I install laravel subscriptions  
I get this
 download rinvex/tmp-felixkiss-uniquewith-validator from dist: The "https://api.github.com/repos/rinvex/tmp-felixkiss-uniquewith-validator/zipball/004ec4ae0995c9feeafc463d247a2e357d98afa5" file could not be downloaded (HTTP/1.1 404 Not Found)
 
 Installing rinvex/tmp-felixkiss-uniquewith-validator (3.4.3): Cloning 004ec4ae09
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+vmi511684.contaboserver.net+2021-06-19+0816
to retrieve a token. It will be stored in "/home/suqaljameuh/.config/composer/auth.json" for future use by Composer.

**Comment by muhamedRadwan** [comment]
@Omranic @ppalmeida  any help ?

**Comment by ppalmeida** [comment]
Hey, @muhamedRadwan. Thank you for your message.

Actually I tried to use this package but in the end I implemented it by hand in my project. So I can't help you, since I'm not using it. But I know rinvex people are awesome and I hope they'll help you asap.

Cheers!

**Comment by Omranic** [comment]
Thank you @ppalmeida 

Hello @muhamedRadwan, you're probably using an old version of the package, please use the latest release v5.x as that not-found dependency is no longer required by the latest release. Make sure you've the required PHP version v7.4 at least and Laravel v8.x
