### ISSUE TITLE
need flexible pricing for plan and addon implementation example

### ISSUE THREAD

**Issue by abanghendri** [rinvex/laravel-subscriptions#157]
Hi, thanks for the awesome package. 
I have some questions, how to use this package for (let's say):

1. user can get different prices on different time periods (like: $5/month, but if you billed annually you will be charged $3/month as well)
2. user can choose addons for the plans (think like hosting, we can choose addons like domain, Cpanel, SSL, or other services and will increase the invoice)

How to achieve these cases? do I need different plans for each period and addon?

**Comment by Omranic** [comment]
Thank you @abanghendri 

Well, these are good questions, here's my feedback:

1. This is a nice feature planned for the future, but currently it's not implemented. I'd be happy to look into any PRs adding this to the package.

2. The addons idea is implemented as plan features, but missing the pricing modification, I believe this should be easy to add support for pricing as well. Like the previous point, I'd be happy if someone can submit a PR for this.

Please feel free to reopen or submit PRs for this package 😉
