### ISSUE TITLE
Renew Subscription and try to use record feature usage, Unique Key constraint voilation

### ISSUE THREAD

**Issue by mirza4027** [rinvex/laravel-subscriptions#159]
I am trying to renew a plan subscription, once it's renewed on trying to call the recordFeatureUsage method in PlanSubscription Model gives me the unique constraint violation. Since renewing the plan subscription leads to soft delete of plan subscription usage, therefore it does not allow new entry to be created in plan_subscription_usage table. Is there any workaround for it?

**Comment by Omranic** [comment]
This seems to me related to #76, so I'll close and keep the discussion there. Feel free to re-open & explain if it's not.
