### ISSUE TITLE
sort_order doesnt take the value i have given it take increment value automatically  in version 4.1.0 any help ?

### ISSUE THREAD

**Issue by harshad4118** [rinvex/laravel-subscriptions#163]
in version 4.1.0 sort_order in plan and planfeatures dosent take custom it take increment value automatically  in version 4.1.0 any help ?

**Comment by harshad4118** [comment]
in version 4.1.0 sort_order in plan and planfeatures dosent take custom it take increment value automatically  in version 4.1.0 any help ?

**Comment by Omranic** [comment]
I'm not sure that's accurate. If I understand correctly, both Plan & PlanFeature models takes custom values for `sort_order`, as it's fillable and could get any valid numeric value passed. Check:
https://github.com/rinvex/laravel-subscriptions/blob/master/src/Models/Plan.php#L99
https://github.com/rinvex/laravel-subscriptions/blob/master/src/Models/PlanFeature.php#L74

Please let me know if that's not what you mean, or if you need further help.

**Comment by harshad4118** [comment]
> I'm not sure that's accurate. If I understand correctly, both Plan & PlanFeature models takes custom values for `sort_order`, as it's fillable and could get any valid numeric value passed. Check:
> https://github.com/rinvex/laravel-subscriptions/blob/master/src/Models/Plan.php#L99
> https://github.com/rinvex/laravel-subscriptions/blob/master/src/Models/PlanFeature.php#L74
> 
> Please let me know if that's not what you mean, or if you need further help.

i understand that it take custom value for sort_order in both model but in my case its not working according to you described above and it take increment value even if i pass some custom numeric value

**Comment by Omranic** [comment]
You can check [spatie/eloquent-sortable](https://github.com/spatie/eloquent-sortable) for documentation, as this package depends on that one.
