### ISSUE TITLE
whats different starts_at and trial_ends_at

### ISSUE THREAD

**Issue by yogithesymbian** [rinvex/laravel-subscriptions#167]
my json
```
        "id": 1,
        "subscriber_type": "App\\Models\\User",
        "subscriber_id": 2,
        "plan_id": 2,
        "slug": "freetrial7day",
        "name": "freetrial7day",
        "description": null,
        "trial_ends_at": "2021-09-06T22:53:54.000000Z",
        "starts_at": "2021-09-06T22:53:54.000000Z",
        "ends_at": "2021-09-07T22:53:54.000000Z",
        "cancels_at": null,
        "canceled_at": null,
        "timezone": null,
        "created_at": "2021-08-30T22:53:54.000000Z",
        "updated_at": "2021-08-30T22:53:54.000000Z",
        "deleted_at": null
```

and why my renew() `// $cancel = $user->subscription($slug)->cancel();` 
and didnt update the `trial_ends_at`  into 7 day against (renew) , only `touch updated_at` .

**Comment by Omranic** [comment]
Thank you for your patience. The trial features aren't implemented in the best way, and it's lacking fundamental logic. I'd be happy to consider any PRs to improve the implementation of this feature. All PRs are welcome 😉

Added to the readme roadmap in case someone is willing to contribute
https://github.com/rinvex/laravel-subscriptions/tree/develop#roadmap
