### ISSUE TITLE
ERROR: There are no commands defined in the "rinvex:publish" namespace

### ISSUE THREAD

**Issue by chegmarco1989** [rinvex/laravel-subscriptions#168]
Hi.

We are trying to install "**Rinvex/Laravel-subscripions**". But when we run the command:

> php artisan rinvex:publish:subscriptions

**We receive the following error:**

> There are no commands defined in the "rinvex:publish" namespace.

Can you give soot to this problem to help us finalize the package installation without error ???
Thanks in advance.

**Comment by Omranic** [comment]
This should be fixed in recent releases, make sure you're using v6+ of the package.
