### ISSUE TITLE
How to get user current subscription

### ISSUE THREAD

**Issue by japhyamg** [rinvex/laravel-subscriptions#172]
Good day, please how can i get the user current active subscription not subscriptions.

**Comment by 6ichem** [comment]
Hi, I have made a PR for this feature to be added into the package. In the meantime you can use it as I explained in the PR: https://github.com/rinvex/laravel-subscriptions/pull/173

**Comment by Omranic** [comment]
@6ichem Merged, thank you!

@japhyamg let me know if you still need help.

**Comment by japhyamg** [comment]
ok thank you

**Comment by Fayozjon** [comment]
Not working

**Comment by akunbeben** [comment]
> @6ichem Merged, thank you!

@Omranic any information on when it will publish? I was having a hard time trying to extend the model with that PR's code 😭

**Comment by Omranic** [comment]
@akunbeben @Fayozjon @6ichem @japhyamg it's now tagged as a new release, check v6.1.0
