### ISSUE TITLE
Trait "Rinvex\Subscriptions\Traits\HasPlanSubscriptions" not found

### ISSUE THREAD

**Issue by sheinfeld** [rinvex/laravel-subscriptions#174]
I don't understand what's going on...

https://i.imgur.com/qrIwt1c.png

Any ideas? I've already tried composer dump-autoload and update

**Comment by insign** [comment]
Have you checked if this still the class name? Last month the repo had some
name changes...

**Comment by Omranic** [comment]
@sheinfeld latest release had breaking-change and renamed classes/methods. Check all changes here https://github.com/rinvex/laravel-subscriptions/compare/v6.0.0...v6.0.1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
