### ISSUE TITLE
Problem with installation on Laravel 7

### ISSUE THREAD

**Issue by faramarzQ** [rinvex/laravel-subscriptions#176]
Well i'm facing this error while installing the package on Laravel 7.*, 
`rinvex/laravel-subscriptions v2.0.0 requires illuminate/console ~5.8.0 -> found illuminate/console[v5.8.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require`
How can i resolve it?

**Comment by Fayozjon** [comment]
+

**Comment by Omranic** [comment]
The currently supported versions are Laravel v8+ and PHP v8.1+

So you'll need to use an older version compatible with Laravel v7, and check the PHP version compatibility too.
