### ISSUE TITLE
HasPlanSubscriptions Error

### ISSUE THREAD

**Issue by rapcrown** [rinvex/laravel-subscriptions#182]
Hello,

Laravel 8 install and error ? 

```
Symfony\Component\ErrorHandler\Error\FatalError
Trait 'Rinvex\Subscriptions\Traits\HasPlanSubscriptions' not found

```

**Comment by rapcrown** [comment]
Change name 

```
use Rinvex\Subscriptions\Traits\HasSubscriptions;

 use HasSubscriptions;
```

**Comment by Omranic** [comment]
That shouldn't be the case, latest version uses `HasPlanSubscriptions` but you should be using a compatible version of PHP/Laravel

**Comment by Aslam97** [comment]
> That shouldn't be the case, latest version uses `HasPlanSubscriptions` but you should be using a compatible version of PHP/Laravel

Hi thank you so much for this package. I've question when will v6 is the default install version for this package?

**Comment by Omranic** [comment]
> Hi thank you so much for this package. I've question when will v6 is the default install version for this package?

Hmmmm, it is already! 🤔

**Comment by Aslam97** [comment]
> > Hi thank you so much for this package. I've question when will v6 is the default install version for this package?
> 
> Hmmmm, it is already! thinking

Sorry my fault. didnt know v6 require php 8. as my php version is 7.4 ofcouse composer install automaticlly installed v5 hehe.
