### ISSUE TITLE
Period: $this->interval null point exception

### ISSUE THREAD

**Issue by ppalmeida** [rinvex/laravel-subscriptions#24]
Hi.

In Period class (https://github.com/rinvex/subscriptions/blob/e4f576a2bfcead24d00a462059253c7886fa9157/src/Services/Period.php#L64) the field $this->interval is never updated in the constructor. This is leading to a NULL point exception.

Should it not have a 
```php 
$this->interval = $interval
```
somewhere?

**Comment by javierrivarola** [comment]
Same issue here

**Comment by ayimdomnic** [comment]
was this fixed?

**Comment by Omranic** [comment]
Fixed in https://github.com/rinvex/laravel-subscriptions/pull/27
