### ISSUE TITLE
Period interval translates to wrong Carbon method

### ISSUE THREAD

**Issue by jcoetsie** [rinvex/laravel-subscriptions#28]
the period intervals (d,w,m,y) are used to create a Carbon method to add the interval:

`$test->addDays(3);`

However the code generates: `$test->addDs(3);` and fails.

**Comment by jcoetsie** [comment]
hi,

 I opened a pull request with some changes but it keeps on failing on your checks.
I have no idea why. Can you check please?

tx

**Comment by msyahidin** [comment]
@jcoetsie hi, is your repo has fixed the issue?

**Comment by Omranic** [comment]
Fixed in latest releases
