### ISSUE TITLE
How can i update Plan ?

### ISSUE THREAD

**Issue by tarangpatel61** [rinvex/laravel-subscriptions#32]
How can i update Plan ?

**Comment by akhzarjaved** [comment]
Got any solution on how to update saveMany ? @tarangpatel61

**Comment by Omranic** [comment]
You can update plans easily like any eloquent model https://laravel.com/docs/8.x/eloquent#updates

If you're asking about changing subscription plan, you can check this https://github.com/rinvex/laravel-subscriptions#change-the-plan
