### ISSUE TITLE
Method Illuminate\Support\Carbon::addMs does not exist.

### ISSUE THREAD

**Issue by freddygenicho** [rinvex/laravel-subscriptions#35]
```
$plan = app('rinvex.subscriptions.plan')->find($id);
$subscription = auth()->user()->newSubscription('main', $plan);
```
How do i reslove this issue? Please i need instant help

**Comment by devingray** [comment]
Same Issue.

**Comment by SmokinB** [comment]
Thats a bug. You can fix it by changing one line code in the Period-Class Constructor:

`$this->interval = in_array($interval, ['d', 'w', 'm', 'y']) ? $interval : 'm';`

to

`$this->interval = in_array($interval, ['day', 'week', 'month', 'year']) ? $interval : 'month';`

**Comment by Omranic** [comment]
Fixed in latest release
