### ISSUE TITLE
laravel 5.6 use this plugin which dependends on rinvex/cacheable but the cacheable now is 5.7 

### ISSUE THREAD

**Issue by guoxiangke** [rinvex/laravel-subscriptions#38]
![image](https://user-images.githubusercontent.com/1160703/45971890-cb9f0f00-c06c-11e8-9d83-1039697ce7a7.png)

**Comment by guoxiangke** [comment]
https://github.com/rinvex/subscriptions/blob/f9bb8dbf6eb905b3c55aa310195748fc0566bf0f/composer.json#L44

**Comment by Omranic** [comment]
@guoxiangke yes, but you can lock package version to *v0.0.4* that fully supports Laravel v5.6 :)

**Comment by Omranic** [comment]
We try to keep `develop` branch always up to date.

This package is now supports Laravel v5.7 so will close this issue.
