### ISSUE TITLE
I think here should be $interval  instead of $this->interval .

### ISSUE THREAD

**Issue by guoxiangke** [rinvex/laravel-subscriptions#42]
https://github.com/rinvex/laravel-subscriptions/blob/23697d08117d01b30878b7ef55817bf8a8478982/src/Services/Period.php#L63

**Comment by guoxiangke** [comment]
>>> $user->newSubscription('main', $plan);
TypeError: ucfirst() expects parameter 1 to be string, null given

**Comment by Karan1458** [comment]
I think maintainer is not active. Otherwise someone has already reported this issue in past months.
 
[Pull Request](https://github.com/rinvex/laravel-subscriptions/pull/27)

**Comment by Omranic** [comment]
Fixed in #27

**Comment by ProjectInfinity** [comment]
Why was this not merged into master and released with 1.0.1? This is still unusable because $this->interval is null.

**Comment by Omranic** [comment]
@ProjectInfinity Done https://github.com/rinvex/laravel-subscriptions/releases/tag/v1.0.2
