### ISSUE TITLE
BadMethodCallException on byFeatureSlug

### ISSUE THREAD

**Issue by SidneySaints** [rinvex/laravel-subscriptions#43]
$user = $request->user();
$subscription = $user->subscription('main');
$feature = sprintf('%s-%s', $subscription->plan->name, $feature);

return $subscription->canUseFeature($feature);

i get this error:

"Call to undefined method Illuminate\Database\Eloquent\Relations\HasMany::byFeatureSlug()"

**Comment by armandohg** [comment]
Were you able to find a solution for this?

**Comment by karol-pietrzak** [comment]
@armandohg please see https://github.com/rinvex/laravel-subscriptions/issues/62#issuecomment-516094623

**Comment by Omranic** [comment]
Similar to #43 #48 #62 #65 #136 #137 and was fixed previously on 0714e73, the fix already exists on the `develop` branch.

I'll tag a new version to merge the fix from `develop` to `master` 👍 

Check here for details 
https://github.com/rinvex/laravel-subscriptions/blob/c11e6bb85fcd5dcf706cb7544e0d375654868bbb/src/Models/PlanSubscriptionUsage.php#L132-L137
