### ISSUE TITLE
Call to undefined method guardAgainstUntranslatableAttribute()

### ISSUE THREAD

**Issue by moharrum** [rinvex/laravel-subscriptions#46]
Hi,

After upgrading `spatie/laravel-translatable` to 3.1, creating a new `Plan` model returns `Call to undefined method guardAgainstUntranslatableAttribute()`.

I'm wondering why you are using `rinvex/laravel-support` `HasTranslations` trait instead of `spatie` and simply override in `Plan.php`.

Plus, `HasTranslations.php` definition of `getTranslations` method now does not match `spatie/laravel-translatable: ^3.1`,

**Comment by Omranic** [comment]
This issue doesn't relate to this package, but relates to `rinvex/laravel-support`

Fixed anyway in recent releases and it's now working fine :)

**Comment by moharrum** [comment]
I know it does not relate to this package, but still it is affected. BTW, the trait used in `laravel-support` is not necessary anyway, you can override methods directly in the model class, and make our lives easier I guess :).
