### ISSUE TITLE
BadMethodCallException Call to undefined method Rinvex\Subscriptions\Models\Plan::getFeatureByName()

### ISSUE THREAD

**Issue by namdeveloper** [rinvex/laravel-subscriptions#48]
![image](https://user-images.githubusercontent.com/4077740/50644174-a6db0180-0fa2-11e9-8d96-c2723f103f15.png)

$plan = app('rinvex.subscriptions.plan')->find(1);
        //$plan4 = app('rinvex.subscriptions.plan')->find(4);

        // Get all plan features  
        echo 'Get all plan features: ';              
        echo $plan->features;
        echo '<br/>';

        // Get all plan subscriptions
        echo 'Get all plan subscriptions: ';
        echo $plan->subscriptions;
        echo '<br/>';

        // Check if the plan is free
        echo 'Check if the plan is free: ';
        echo $plan->isFree();
        echo '<br/>';

        // Check if the plan has trial period
        echo 'Check if the plan has trial period: ';
        echo $plan->hasTrial();
        echo '<br/>';

        // Check if the plan has grace period
        echo 'Check if the plan has grace period: ';
        echo $plan->hasGrace();
        echo '<br/>';
       
        $amountOfPictures = $plan->getFeatureByName('referencing_my_places_and_my_programming')->value;

**Comment by pete001** [comment]
Use `getFeatureBySlug`

**Comment by jlsodai** [comment]
You can query `getFeatureBySlug` directly:
$plan->features()->where('slug', 'referencing_my_places_and_my_programming')->first()

**Comment by Omranic** [comment]
Thank you for your patience, this is now fixed in https://github.com/rinvex/laravel-subscriptions/commit/0714e737f8738b90e52fbd983478f6ba6f85757f

The right code to use is `    $amountOfPictures = $plan->getFeatureBySlug('referencing_my_places_and_my_programming')->value;`
