### ISSUE TITLE
rinvex.subscriptions.plan_subscription does not exist

### ISSUE THREAD

**Issue by ervaibhavsinghal** [rinvex/laravel-subscriptions#49]
@Omranic Thanks for this awesome plugin, but we got same error in this plugin.

we required the plan name which has been subscribed by the user, so we are tring to get this

`$user = Auth::id();`
 `$bookingsOfUser = app('rinvex.subscriptions.plan_subscription')->ofUser($user)->get();`

but got an error:

> ReflectionException (-1)
Class rinvex.subscriptions.plan_subscription does not exist

![screenshot from 2019-01-31 20-08-15](https://user-images.githubusercontent.com/16643006/52061586-a4b19600-2594-11e9-9ace-e79a51a01dd0.png)

If anybody knows the solution, let me know. Thanks in advance.

**Comment by ervaibhavsinghal** [comment]
@Omranic thanks for your response... now it's working fine to just change the line with
old line: 
`$bookingsOfUser = app('rinvex.subscriptions.plan_subscription')->ofUser($user)->get();`

New Line:
`$bookingsOfUser = app('rinvex.subscriptions.plan_subscriptions')->ofUser($user)->get();`

"s" is missing in that code.

**Comment by Omranic** [comment]
Oh sorry! This is fixed 10e106890b6226235824e27ac4b44436e26c241b thanks to your highlight @ervaibhavsinghal 🙂
