### ISSUE TITLE
Dispatcher::fire() is not a function

### ISSUE THREAD

**Issue by kunaldodiya** [rinvex/laravel-subscriptions#54]
I am using laravel 5.8, just installed it, while adding plans, it gives me this error

![image](https://user-images.githubusercontent.com/7272013/53976855-d981b180-412d-11e9-84d8-4a7386d45a2a.png)

**Comment by kunaldodiya** [comment]
hi, if i manually change psr4 => laravel-cachable folder in your composer.json file to your latest [laravel-cacheble](https://github.com/rinvex/laravel-cacheable) repository, the error resolves immediately

**Comment by Omranic** [comment]
This should be fixed now, feel free to re-open if you still face any issues.
https://github.com/rinvex/laravel-subscriptions/releases
