### ISSUE TITLE
rinvex/laravel-subscriptions v2.0.0 requires rinvex/laravel-support ^2.0.0 

### ISSUE THREAD

**Issue by odaiderawi** [rinvex/laravel-subscriptions#57]
![image](https://user-images.githubusercontent.com/36736057/56044035-0b96bc80-5d47-11e9-8fa7-113a24d09962.png)

**Comment by Omranic** [comment]
Yes, this package version `rinvex/laravel-subscriptions` v2.0.x requires requires `rinvex/laravel-support` ^2.0.x which requires Laravel v5.8.x .. you may need to consider upgrading your Laravel installation, or use this package's v1.0.x branch.
