### ISSUE TITLE
How disable the translation for entire package

### ISSUE THREAD

**Issue by rajeshdk** [rinvex/laravel-subscriptions#58]
Hi,
Hope you are doing well?
How to disable the translation for the entire package - like create a plan , as it creates an extra burden for plan name when I fetch it directly.

$plan = app('rinvex.subscriptions.plan')->create([
    'name' => 'Pro',
    'description' => 'Pro plan',
    'price' => 9.99,
    'signup_fee' => 1.99,
    'invoice_period' => 1,
    'invoice_interval' => 'month',
    'trial_period' => 15,
    'trial_interval' => 'day',
    'sort_order' => 1,
    'currency' => 'USD',
]);

In database it creates plan name as {"en":"Pro"} - I want only Pro

Thanks in advance
Warm Regards

**Comment by Omranic** [comment]
Most of our packages depends on translations, and it's honestly easy to use and get what you want, check documentation for the translatable package [here](https://github.com/spatie/laravel-translatable). If you still want to remove translations features completely, consider forking the package 🙂
