### ISSUE TITLE
Paying for a plan x times

### ISSUE THREAD

**Issue by rylxes** [rinvex/laravel-subscriptions#64]
How can i pay for a plan x times, e.g monthly bill, but i want to pay for 6 months , ... but i dont want to create a subscription record for it because its a one off occurrence

**Comment by chinedu117** [comment]
Am thinking of creating a SubscriptionManager wrapper class that manages users subscription

**Comment by Omranic** [comment]
This is currently not implemented, but I'd be happy to consider a PR for that. All PRs are welcome 😉

Added to the readme roadmap in case someone is willing to contribute
https://github.com/rinvex/laravel-subscriptions/tree/develop#roadmap
