### ISSUE TITLE
Renew need to calculate remaining days for extend

### ISSUE THREAD

**Issue by fatihalp** [rinvex/laravel-subscriptions#66]
If you extend user's package it's renewing 1 month from now. We don't have automatic payment. 

If user have 3 weeks already, user lose it's remaning days. We need end_data to be 1 month+3 week to be fair if user renewing before end date.

**Comment by fignewton** [comment]
I second this. I would also have liked to give users the option to renew before their current subscription ends. for this to work `renew()` (or an alternative method) should add the period the end of the existing one, instead of just calculating from the current date.

**Comment by Omranic** [comment]
Thank you @fatihalp for highlighting this, and I agree that we need to tweak the current logic to include this feature. This is related to #139 

I would be happy to consider any PRs adjusting the current logic to accommodate this new feature. Any help would be appreciated.
