### ISSUE TITLE
How to use trial period

### ISSUE THREAD

**Issue by lutov** [rinvex/laravel-subscriptions#67]
Is trial period feature actually available? There is a field in database and trial period is somehow used in calculations of subscription status. But I failed to find any information about how to start trial but not the subscription itself.

For example, if my plan has 1 month invoice period and a 7-day trial period, and I create a new subscription to this plan, then that subscription would be active for 1 month and 7 days? How can I automatically ask user for actual payment, when trial ends?

**Comment by lutov** [comment]
OK, so I performed some tests, and that's exactly what happened: value of the trial_period field is beeing simply added to the ends_at value of the subscription. And method onTrial() on subscription returns "true" whether plan has or hasn't trial_period value bigger then 0.

I don't really get the reason why trial period affects overall subscription length. In my mind it should be separate entities, that excludes each other.

**Comment by Omranic** [comment]
Thank you for your patience, this is currently not implemented in the best way, but it's on the roadmap. I'd be happy to consider PRs to improve the implementation of this feature. All PRs are welcome 😉

**Comment by Omranic** [comment]
Added to the readme roadmap in case someone is willing to contribute https://github.com/rinvex/laravel-subscriptions/tree/develop#roadmap
