### ISSUE TITLE
Prorata usage

### ISSUE THREAD

**Issue by abishekrsrikaanth** [rinvex/laravel-subscriptions#68]
I see the plan table has fields for maintaining Prorata config. Is there any docs on its usage or is this feature still pending?

**Comment by undjike** [comment]
I have the same preoccupation. Need documentation or usage examples.

**Comment by Omranic** [comment]
Despite having the db fields, this feature isn't implemented yet. I'd be happy to consider PRs adding this feature, all PRs are welcome 😉
