### ISSUE TITLE
Slug column is unique, documentation uses it as a query

### ISSUE THREAD

**Issue by ionutcalara** [rinvex/laravel-subscriptions#69]
In the documentation you mention this type of call a lot. This for me meant that i could query the subscription by its slug and not id which is true. But its quite not what you expect as slugs are unique, so this would not be practical if you have multiple users, as the following user would get `main-1` and so on. 

```
$user->subscription('main')
```

**Comment by Omranic** [comment]
This is related to #76 & #110 (fix under review, let's keep the discussion on #76)
