### ISSUE TITLE
FatalThrowableError on php7.4 laravel 6.0

### ISSUE THREAD

**Issue by mrlinnth** [rinvex/laravel-subscriptions#77]
```
syntax error, unexpected 'SlugOptions' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
```

Facing above error after upgrading my php version to 7.4.

**Comment by ricard-pons** [comment]
Got the same issue with another package earlier today. Make sure you are running php 7.4.

Try to call phpinfo();

In my case, using Laravel Valet, `php -v` was showing 7.4 but the phpinfo() function was using 7.3 due to a conflict with homebrew.

**Comment by mrlinnth** [comment]
Ok this might be another package's bug/issue. My previous comment was not complete.
The error is actually related to slugabble package as shown below.

![screenshot-2020 01 07-10_00_06](https://user-images.githubusercontent.com/4952597/71866644-4cd0c700-3135-11ea-94b4-00a0f7143b9d.png)

I have changed valet to use php 7.3 and my phpinfo() is also showing 7.3. But this still occurred. I guess I will submit an issue at Sluggable repo.
