### ISSUE TITLE
Request for PHP 7.3 and Laravel 6 support version

### ISSUE THREAD

**Issue by mrlinnth** [rinvex/laravel-subscriptions#80]
Not a lot of other laravel packages are ready for php 7.4.

I have been using your package since last year without any issue. 

After php 7.4 is out, this package together with depending packages like (laravel-sluggable and laravel-support, etc) has updated for php 7.4.

I have submitted and closed an issue on this repo recently with a syntax error issue. After tracing the bug, I found out that it is because I am on php 7.3. Once I switched to php 7.4 everything is fine.

I have other packages which will break on php 7.4, so I cannot use this package anymore. 

It will be really great if there is a version that work with php 7.3 and laravel 6.

**Comment by Omranic** [comment]
Hello @mrlinnth, thank you for your message.
Honestly I don't understand what's your problem exactly, as this package requires only PHP v7.2 and Laravel v6.x which means you can use it with PHP v7.3 & v7.4 without any issues.

Please feel free to reopen if there's anything we can help you with, or feel free to submit a PR in case you're willing to help fix what you believe is broken 🙂

**Comment by VivekShingala** [comment]
No, it doesn't work with PHP 7.3

**Comment by Omranic** [comment]
As of this moment, Laravel v7.x is supported in v4.x of this package, which also requires PHP v7.4 or up.
