### ISSUE TITLE
Laravel 5.8 Support

### ISSUE THREAD

**Issue by chrisidakwo** [rinvex/laravel-subscriptions#81]
What's the rationale behind enforcing Laravel ^6.0? Why not provide support for, at least from, v5.5 upwards?

Plus your releases are not descriptive enough for one to know where you started enforcing ^6.0 so I can just easily pull the release before that.

**Comment by Omranic** [comment]
Thank you for your question, you can always refer back to the Changelog for details on each release, and to track any changes or Laravel compatibility. If you've suggestions to make it more clear please feel free to send a PR 😉 [CHANGELOG](https://github.com/rinvex/laravel-subscriptions/blob/master/CHANGELOG.md)
