### ISSUE TITLE
Plan features for relationship table

### ISSUE THREAD

**Issue by debuGhy** [rinvex/laravel-subscriptions#84]
Suppose I have a user and user_image table. I have created a plan with feature for limiting the user to upload a particular number of images, then how can I achieve the same? How can I check if the user has uploaded the maximum number of image for that plan? How to check the plan usage? The user will upload the image in user_image table.

**Comment by hkan** [comment]
See [Subscription Feature Usage](https://github.com/rinvex/laravel-subscriptions#subscription-feature-usage) section and the next two in the documentation.

**Comment by debuGhy** [comment]
thanks for the update. Already did that.
