### ISSUE TITLE
Disable caching

### ISSUE THREAD

**Issue by darkmat13r** [rinvex/laravel-subscriptions#85]
I want to disable the caching.

**Comment by gautamsolankidev** [comment]
There's a quick fix I found to disable cache 
Goto: Vendor\rinvex\laravel-subscriptions\src\Models\PlanSubscription.php

and remove use CacheableEloquent;

**Comment by darkmat13r** [comment]
> There's a quick fix I found to disable cache
> Goto: Vendor\rinvex\laravel-subscriptions\src\Models\PlanSubscription.php
> 
> and remove use CacheableEloquent;

That will be not be a good idea. As we are changing the dependency file it will be updated whenever i will run composer  update

**Comment by darkmat13r** [comment]
Here what i did to disable the caching..  If  someone else is facing same issue..
I created my own class Plan, PlanFeature, PlanSubscription and PlanSubscriptionUsage and extended the rinvex respective classes.
Then in the config  rinvex.subscriptions.php. Changed models to my models
```
// Subscriptions Models
    'models' => [
        'plan' => \App\Models\Plan::class,
        'plan_feature' => \App\Models\PlanFeature::class,
        'plan_subscription' => \App\Models\PlanSubscription::class,
        'plan_subscription_usage' => \App\Models\PlanSubscriptionUsage::class,
    ],

```
Then in our own classes override this method.
```
public function getCacheLifetime(): int
    {
        return 0;
    }
```
