### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by aftandilmmd** [rinvex/laravel-subscriptions#87]
**Any progress in Laravel 7 Support?**

**Comment by turkidkil** [comment]
Installation request for laravel/framework ^7.0

https://ibb.co/jMwJZFK

![alt text](https://i.ibb.co/NjNTnzh/Screen-Shot-1441-07-23-at-1-40-46-PM.png)

**Comment by Omranic** [comment]
All packages has been upgraded to support Laravel v7.x already, please double check and let me know if you still need any help.

**Comment by shadracnicholas** [comment]
Still not working

![Screenshot 2020-03-22 at 00 00 20](https://user-images.githubusercontent.com/46599542/77236548-ad1dc380-6bd0-11ea-9c25-5a912e23b132.png)

**Comment by Omranic** [comment]
@shadracnicholas this package is now on version 4.x branch, please make sure to update your compoer requirements 🙂
