### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by bondan23** [rinvex/laravel-subscriptions#89]
I'm facing this kind of issue when running the publisher

<img width="366" alt="Screen Shot 2020-03-23 at 22 27 56" src="https://user-images.githubusercontent.com/13124714/77333212-a8cee300-6d55-11ea-83aa-4397ffcfa27e.png">

I'm Using Laravel `6.18.2`.
Rinve Version : `3.0.1`
Does anyone facing the same issue like me?

Thank you.

**Comment by masksshow** [comment]
Hey. similarly.

**Comment by bondan23** [comment]
> Hey. similarly.

Hey, I think there is something wrong inside the Rinvex v.3.0.1 deps , 
it used `laravel-support` and using the `ConsoleTools` traits, where inside the provider you can see there is a called functions`publishesConfig` and  `publishesMigrations`.

so for temporary fix I just go through inside `laravel-support` directory and did the hard code change.

```php
protected function publishesResources(): bool
{
   return false;
}
```

and inside inside the `PublishCommand.php`, you can change the switch case into this

```php
switch ($this->option('resource')) {
    case 'config':
        $this->call('vendor:publish', ['--tag' => 'rinvex-subscriptions-config', '--force' => $this->option('force')]);
        break;
    case 'migrations':
        $this->call('vendor:publish', ['--tag' => 'rinvex-subscriptions-migrations', '--force' => $this->option('force')]);
        break;
    default:
        $this->call('vendor:publish', ['--tag' => 'rinvex-subscriptions-config', '--force' => $this->option('force')]);
        $this->call('vendor:publish', ['--tag' => 'rinvex-subscriptions-migrations', '--force' => $this->option('force')]);
        break;
}
```

and run the publish again afterward.

**Comment by bondan23** [comment]
> Hey. similarly.

I've found the wayaround, change the `APP_ENV` to `production`

**Comment by gautamsolankidev** [comment]
> > Hey. similarly.
> 
> I've found the way around, change the `APP_ENV` to `production`

Thanks, It Worked! :)

**Comment by Omranic** [comment]
This issue has been fixed in recent release v4.x please test and let me know if you still have any other issues or questions. Feel free to re-open this for more discussion.

**Comment by insign** [comment]
Some months ago this year I lost hours trying to figure out the problem
with migrations. Probably was this issue.

**Comment by Omranic** [comment]
@insign  I hope it's now fixed for you. Let me know if you need any help!
