### ISSUE TITLE
Publish resources migrations and config files not working

### ISSUE THREAD

**Issue by elrosi** [rinvex/laravel-subscriptions#96]
Hi, 
in Laraveli 6, following the php artisan rinvex: migrate: subscriptions command, the following error occurs: _There are no commands defined in the "rinvex:migrate" namespace._

There is also no need to execute the php artisan vendor: publish command when installing?

Thank you for your response.

**Comment by minkbear** [comment]
Got same problems too.

**Comment by MouadZIANI** [comment]
It will be fixed by changing `APP_ENV` to `production`.

**Comment by minkbear** [comment]
@MouadZIANI Yes, That's work, Thank you.

**Comment by Omranic** [comment]
This issue has been fixed in recent release v4.x please test and let me know if you still have any other issues or questions. Feel free to re-open this for more discussion.

**Comment by BrunoGGM** [comment]
php artisan rinvex:migrate:subscriptions
 

> ************************************************
> *     Migrate Rinvex Subscriptions Tables.     *
> ************************************************
> 
> Migrating: 2020_06_17_205554_create_plans_table
> 
>    Illuminate\Database\QueryException 
> 
>   SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` int unsigned not null auto_increment primary key, `slug` varchar(255) not null, `name` json not null, `description` json null, `is_active` tinyint(1) not null default '1', `price` decimal(8, 2) 
> not null default '0.00', `signup_fee` decimal(8, 2) not null default '0.00', `currency` varchar(3) not null, `trial_period` smallint unsigned not null default '0', `trial_interval` varchar(255) not null default 'day', `invoice_period` smallint unsigned not null default '0', `invoice_interval` varchar(255) not null default 'month', `grace_period` smallint unsigned not null default '0', `grace_interval` varchar(255) not null default 'day', `prorate_day` 
> tinyint unsigned null, `prorate_period` tinyint unsigned null, `prorate_extend_due` tinyint unsigned null, `active_subscribers_limit` smallint unsigned 
> null, `sort_order` mediumint unsigned not null default '0', `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
> 
>   at D:\EEEC\vendor\laravel\framework\src\Illuminate\Database\Connection.php:671
>     667|         // If an exception occurs when attempting to run a query, we'll format the error
>     668|         // message to include the bindings with SQL, which will make this exception a
>     669|         // lot more helpful to the developer instead of just the database's errors.
>     670|         catch (Exception $e) {
>   > 671|             throw new QueryException(
>     672|                 $query, $this->prepareBindings($bindings), $e
>     673|             );
>     674|         }
>     675|
> 
>   1   D:\EEEC\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458
>       PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''")
> 
>   2   D:\EEEC\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458
>       PDO::prepare("create table `` (`id` int unsigned not null auto_increment primary key, `slug` varchar(255) not null, `name` json not null, `description` json null, `is_active` tinyint(1) not null default '1', `price` decimal(8, 2) not null default '0.00', `signup_fee` decimal(8, 2) not null default '0.00', `currency` varchar(3) not null, `trial_period` smallint unsigned not null default '0', `trial_interval` varchar(255) not null default 'day', `invoice_period` smallint unsigned not null default '0', `invoice_interval` varchar(255) not null default 'month', `grace_period` smallint unsigned not null default '0', `grace_interval` varchar(255) not null default 'day', `prorate_day` tinyint unsigned null, `prorate_period` tinyint unsigned null, `prorate_extend_due` tinyint unsigned null, `active_subscribers_limit` smallint unsigned null, `sort_order` mediumint unsigned not null default '0', `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'")
